image: docker:19.03.11

stages:
  - test

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod/

unit_test:
  stage: test
  image: golang:1.15.0-alpine
  extends: .go-cache
  services:
    - name: mysql:8.0
      alias: mysql
  variables:
    MYSQL_DATABASE: "integration"
    MYSQL_ROOT_PASSWORD: "password"
  script:
    - cat /etc/hosts
    - if ! [ -d "./database/mysql/migrate_test" ]; then mkdir ./database/mysql/migrate_test; fi
    - cp ./database/mysql/migrateTest/* ./database/mysql/migrate_test
    - cp ./database/mysql/migrations/* ./database/mysql/migrate_test
    - CGO_ENABLED=0 GOOS=linux go test --tags=integration -count=1 ./...